spring:
  profiles:
    active:
    - 'live'

---
logging:
  file:
    path: ./log/
spring:
  profiles: test
  datasource:
    name: videotransfert-db-test
    url: jdbc:h2:mem:videotransfert-db-test
    username: sa
    password: 
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
media-batch:
    paths:
        # Comma separated list where batch will lookup for files to classify
        start-root-dirs: 'src/test/resources/spring-media-batch' #not used in test mode
        destination-root-dir-photo: 'src/test/resources/spring-media-batch'
        destination-root-dir-video: 'src/test/resources/spring-media-batch'
---
logging:
  file:
    path: /var/log/spring-media-batch
spring:
  profiles: local
  datasource:
    name: videotransfert-db-test
    url: jdbc:h2:mem:videotransfert-db-test
    username: sa
    password: 
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
media-batch:
    paths:
        start-root-dirs: '/home/dev/spring-media-batch/source'
        destination-root-dir-photo: '/home/dev/spring-media-batch/destination-photo'
        destination-root-dir-video: '/home/dev/spring-media-batch/destination-video'    
---
logging:
  file:
    path: /var/log/spring-media-batch
spring:
  profiles: live
  datasource:
    name: videotransfert-db-test
    url: jdbc:h2:mem:videotransfert-db-test
    username: sa
    password: 
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
media-batch:
    paths:
        start-root-dirs: '/volume1/photo/A_CLASSER,/volume1/photo/phone_JeanPaul,/volume1/photo/phone_arlette,/volume1/photo/phone_elena,/volume1/photo/tablette_lg'
        destination-root-dir-photo: '/volume1/photo'
        destination-root-dir-video: '/volume1/video/Famille'   
   