spring:
  profiles:
    active:
    - 'live'

---
logging:
  file:
    path: ./log/
  config: src/test/resources/logback-test-spring.xml
spring:
  profiles: test
  datasource:
    platform: test
    name: spring-media-batch-ds
    url: jdbc:h2:mem:spring-media-batch-db
    username: sa
    password: 
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
    initialization-mode: always
  liquibase:  
    enabled: false
media-batch-organizer:
    paths:
        # Comma separated list where batch will lookup for files to classify
        start-root-dirs: 'src/test/resources/spring-media-batch' #not used in test mode
        destination-root-dir-photo: 'src/test/resources/spring-media-batch'
        destination-root-dir-video: 'src/test/resources/spring-media-batch'
    file-name-patterns:
        photo-file-name-patterns: '^(IMG-)(\d{8})(-WA)(\d{4})(.jpg|.jpeg)$,^(\d{8})(_)(\d{6})(.jpg|.jpeg)$,^(IMG)(\d{14})(.jpg|.jpeg)$,^(IMG_)(\d{8})(_)(\d{6})(_)(\d{3})(.jpg|.jpeg)$'
        photo-file-name-embedded-date-patterns: '(\d{8}),^(\d{8})(_)(\d{6}),(\d{14}),(\d{8})'
        photo-date-formater-patterns: 'yyyyMMdd,yyyyMMdd_HHmmss,yyyyMMddHHmmss,yyyyMMdd'
media-batch-remove-duplicates-fotos:
    paths:
        # Comma separated list where batch will lookup for duplicates
        start-root-dirs: 'src/test/resources/spring-media-batch' #not used in test mode
---
logging:
  file:
    path: /var/log/spring-media-batch
spring:
  profiles: local
  datasource:
    platform: local
    name: spring-media-batch-ds
    url: jdbc:h2:file:/home/dev/spring-media-batch/database
    username: sa
    password: 
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
  liquibase:  
    change-log: classpath:db/changelog/master.xml    
  h2:
    # Use http://localhost:8080/h2-console to access console
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
media-batch-organizer:
    paths:
        start-root-dirs: '/home/dev/spring-media-batch/source'
        destination-root-dir-photo: '/home/dev/spring-media-batch/destination-photo'
        destination-root-dir-video: '/home/dev/spring-media-batch/destination-video' 
    file-name-patterns:
        photo-file-name-patterns: '^(IMG-)(\d{8})(-WA)(\d{4})(.jpg|.jpeg)$,^(\d{8})(_)(\d{6})(.jpg|.jpeg)$,^(IMG)(\d{14})(.jpg|.jpeg)$,^(IMG_)(\d{8})(_)(\d{6})(_)(\d{3})(.jpg|.jpeg)$'
        photo-file-name-embedded-date-patterns: '(\d{8}),^(\d{8})(_)(\d{6}),(\d{14}),(\d{8})'
        photo-date-formater-patterns: 'yyyyMMdd,yyyyMMdd_HHmmss,yyyyMMddHHmmss,yyyyMMdd'
media-batch-remove-duplicates-fotos:
    paths:
        # Comma separated list where batch will lookup for duplicates
        start-root-dirs: 'src/test/resources/spring-media-batch' 
---
logging:
  file:
    path: /var/log/spring-media-batch
spring:
  profiles: live
  datasource:
    platform: live
    name: spring-media-batch-ds
    url: jdbc:h2:file:/home/spring-media-batch/database
    username: sa
    password: 
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
  liquibase:  
    change-log: classpath:db/changelog/master.xml    
  h2:
    # Use http://localhost:8080/h2-console to access console
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
media-batch-organizer:
    paths:
        start-root-dirs: '/volume1/photo/A_CLASSER,/volume1/photo/phone_JeanPaul,/volume1/photo/phone_arlette,/volume1/photo/phone_elena,/volume1/photo/tablette_lg'
        destination-root-dir-photo: '/volume1/photo'
        destination-root-dir-video: '/volume1/video/Famille'
    file-name-patterns:
        photo-file-name-patterns: '^(IMG-)(\d{8})(-WA)(\d{4})(.jpg|.jpeg)$,^(\d{8})(_)(\d{6})(.jpg|.jpeg)$,^(IMG)(\d{14})(.jpg|.jpeg)$,^(IMG_)(\d{8})(_)(\d{6})(_)(\d{3})(.jpg|.jpeg)$'
        photo-file-name-embedded-date-patterns: '(\d{8}),^(\d{8})(_)(\d{6}),(\d{14}),(\d{8})'
        photo-date-formater-patterns: 'yyyyMMdd,yyyyMMdd_HHmmss,yyyyMMddHHmmss,yyyyMMdd'
media-batch-remove-duplicates-fotos:
    paths:
        # Comma separated list where batch will lookup for duplicates
        start-root-dirs: '/volume1/photo'  
   